### ISSUE TITLE
dont assume all bones are on input

### ISSUE THREAD

**Issue by ghost** [vladmandic/human-motion#1]
pretty self-explanatory

**Comment by vladmandic** [comment]
this project is in preview stage, not yet complete - so yes, that will be added.

**Comment by ghost** [comment]
if its going to be added, dont close it, add it to a milestone and leave it, then when you have done the feature, close the issue

**Comment by vladmandic** [comment]
i start tracking things in github properly once i'm happy with initial release. its a question of personal preference.
